Errors with C++ compilation error
The fieldname is empty

julia> import CxxBulletPrintMWE
[ Info: Precompiling CxxBulletPrintMWE [3b942826-76a3-11e9-350c-7dcfaa477486]
pv = (class btVector3 *) @0x00007f821ce4cdd0

:3:35: error: expected unqualified-id
            auto &r = __juliavar1.;
                                  ^
:3:35: error: expected unqualified-id
            auto &r = __juliavar1.;
                                  ^
:3:35: error: expected unqualified-id
            auto &r = __juliavar1.;
                                  ^
ERROR: LoadError: Tried to Emit Invalid Decl
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] EmitTopLevelDecl(::Cxx.CxxCore.ClangCompiler, ::Cxx.CxxCore.CppPtr{Cxx.CxxCore.CxxQualType{Cxx.CxxCore.CppBaseType{Symbol("clang::Decl")},(false, false, false)},(false, false, false)}) at /Users/goretkin/.julia/dev/Cxx/src/cxxstr.jl:258
 [3] #s37#70 at /Users/goretkin/.julia/dev/Cxx/src/cxxstr.jl:708 [inlined]
 [4] #s37#70(::Any, ::Any, ::Any, ::Any) at ./none:0
 [5] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:522
 [6] macro expansion at /Users/goretkin/.julia/dev/Cxx/src/show.jl:7 [inlined]
 [7] show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Cxx.CxxCore.CppRef{Cxx.CxxCore.CppBaseType{:btVector3},(false, false, false)}) at /Users/goretkin/.julia/dev/Cxx/src/show.jl:9
 [8] #sprint#340(::Nothing, ::Int64, ::Function, ::Function, ::Cxx.CxxCore.CppRef{Cxx.CxxCore.CppBaseType{:btVector3},(false, false, false)}) at ./strings/io.jl:101
 [9] #sprint at ./none:0 [inlined]
 [10] #repr#341 at ./strings/io.jl:208 [inlined]
 [11] repr(::Cxx.CxxCore.CppRef{Cxx.CxxCore.CppBaseType{:btVector3},(false, false, false)}) at ./strings/io.jl:208
 [12] top-level scope at show.jl:555
 [13] include at ./boot.jl:326 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1038
 [15] include(::Module, ::String) at ./sysimg.jl:29
 [16] top-level scope at none:2
 [17] eval at ./boot.jl:328 [inlined]
 [18] eval(::Expr) at ./client.jl:404
 [19] top-level scope at ./none:3
in expression starting at /Users/goretkin/projects/CxxBulletPrintMWEdevcxx/src/CxxBulletPrintMWE.jl:17
ERROR: Failed to precompile CxxBulletPrintMWE [3b942826-76a3-11e9-350c-7dcfaa477486] to /Users/goretkin/.julia/compiled/v1.1/CxxBulletPrintMWE/lJ0ap.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853